name: Auto commit by date

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"  # Setiap jam pada menit ke-0
  workflow_dispatch:  # Tambahkan ini untuk bisa trigger manual

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ini penting untuk memberi izin push
    
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      
      - name: Checkout code
        uses: actions/checkout@v4  # Upgrade ke v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Gunakan token dengan izin write
          fetch-depth: 0

      - name: Setup Git and Commit changes Multi
        run: |
          git config --local user.email "thaariqprs97@gmail.com"
          git config --local user.name "MasThor"
          
          # Array pesan commit acak

          commit_messages=(
            "chore(bot): 😂 commit acak"
            "chore(bot): 😱 daily update"
            "chore(bot): 👿 code maintenance"
            "chore(bot): 💩 cleanup task"
            "chore(bot): 🙏 improvement"
            "chore(bot): 🙈 dependency update"
            "chore(bot): 🐐 optimization"
            "chore(bot): 🤖 automated commit"
            "chore(bot): 🟩 refactoring"
            "chore(bot): 👻 bug fix"
          )
          

          echo "Commit ke-$i - $x pada $(date '+%Y-%m-%d %H:%M:%S')" > LAST_CHANGES
          git add LAST_CHANGES
          
          # Pilih pesan acak
          random_index=$((RANDOM % ${#commit_messages[@]}))
          commit_message="${commit_messages[$random_index]}"
          
          # Buat commit
          git commit -m "$commit_message"
                       
      - name: Push changes
        run: |
          git pull origin main --rebase
          git push origin main
