name: Auto commit by date

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *" 
  workflow_dispatch: 

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      
      - name: Checkout code
        uses: actions/checkout@v4  
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  
          fetch-depth: 0

      - name: Setup Git and Commit changes Multi
        run: |
          git config --local user.email "thaariqprs97@gmail.com"
          git config --local user.name "MasThor"
          
          # Array pesan commit acak

          commit_messages=(
            "😂 what are you looking for on here ?"
            "😱 what are you looking for on here ?"
            "👿 what are you looking for on here ?"
            "💩 what are you looking for on here ?"
            "🙏 what are you looking for on here ?"
            "🙈 what are you looking for on here ?"
            "🐐 what are you looking for on here ?"
            "🤖 what are you looking for on here ?"
            "🟩 what are you looking for on here ?"
            "👻 what are you looking for on here ?"
          )
          

          echo "Commit ke-$i - $x pada $(date '+%Y-%m-%d %H:%M:%S')" > LAST_CHANGES
          git add LAST_CHANGES
          
          # Pilih pesan acak
          random_index=$((RANDOM % ${#commit_messages[@]}))
          commit_message="${commit_messages[$random_index]}"
          
          # Buat commit
          git commit -m "$commit_message"
                       
      - name: Push changes
        run: |
          git pull origin main --rebase
          git push origin main
